spring.application.name=testing.application
server.port=8081
# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/testing_db
spring.datasource.username=postgres
spring.datasource.password=27212564

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect